/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { FocusAnalyticsCreateNestedManyWithoutUsersInput } from "./FocusAnalyticsCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { FocusSessionCreateNestedManyWithoutUsersInput } from "./FocusSessionCreateNestedManyWithoutUsersInput";
import { RewardCreateNestedManyWithoutUsersInput } from "./RewardCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => FocusAnalyticsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FocusAnalyticsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FocusAnalyticsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  focusAnalyticsItems?: FocusAnalyticsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => FocusSessionCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FocusSessionCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FocusSessionCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  focusSessions?: FocusSessionCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => RewardCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RewardCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RewardCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  rewards?: RewardCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
